# Generated by Django 2.1.5 on 2019-01-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EVData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField()),
                ('data_time', models.TimeField()),
                ('data_kW', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
