# Generated by Django 2.1.5 on 2019-01-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='powerData',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('Timestamp', models.DateTimeField()),
                ('Power', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='evdata',
            name='data_kW',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
