# Generated by Django 2.1.5 on 2019-03-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0005_fraserev_healthev_northev'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EVData',
        ),
    ]
