# Generated by Django 2.1.5 on 2019-03-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0008_auto_20190308_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='carData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('totalcars', models.IntegerField()),
                ('chargedcars', models.IntegerField()),
            ],
        ),
    ]
