# Generated by Django 2.1.5 on 2019-03-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0009_cardata'),
    ]

    operations = [
        migrations.CreateModel(
            name='buildingData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=5, max_digits=15)),
            ],
        ),
    ]
