# Generated by Django 2.1.5 on 2019-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0011_auto_20190325_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='buildingEVFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
    ]
