# Generated by Django 2.1.5 on 2019-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0012_buildingevfuture'),
    ]

    operations = [
        migrations.CreateModel(
            name='varDataFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('totalcars', models.IntegerField()),
                ('chargedcars', models.IntegerField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
    ]
