# Generated by Django 2.1.5 on 2019-03-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0013_vardatafuture'),
    ]

    operations = [
        migrations.CreateModel(
            name='chargedCarsData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargedCarsFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsData',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='buildingEVFuture',
            new_name='buildingFuture',
        ),
        migrations.DeleteModel(
            name='BuildingEnergy',
        ),
        migrations.DeleteModel(
            name='carData',
        ),
        migrations.DeleteModel(
            name='EVEnergy',
        ),
        migrations.DeleteModel(
            name='powerData',
        ),
        migrations.DeleteModel(
            name='varDataFuture',
        ),
    ]
