# Generated by Django 2.1.5 on 2019-04-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0014_auto_20190329_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='chargedCarsFraser',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargedCarsFraserFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='chargedCarsHealth',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargedCarsHealthFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='chargedCarsNorth',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargedCarsNorthFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='chargedCarsRose',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargedCarsRoseFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsFraser',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsFraserFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsHealth',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsHealthFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsNorth',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsNorthFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsRose',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='chargingCarsRoseFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('cars', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FraserEVFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HealthEVFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NorthEVFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RoseEVFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='buildingData',
            new_name='building',
        ),
        migrations.RenameModel(
            old_name='chargedCarsData',
            new_name='chargedCarsWest',
        ),
        migrations.RenameModel(
            old_name='chargingCarsFuture',
            new_name='chargedCarsWestFuture',
        ),
        migrations.RenameModel(
            old_name='chargingCarsData',
            new_name='chargingCarsWest',
        ),
        migrations.RenameModel(
            old_name='chargedCarsFuture',
            new_name='chargingCarsWestFuture',
        ),
    ]
