# Generated by Django 2.1.5 on 2019-04-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0015_auto_20190401_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='buildingFraser',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buildingFraserFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buildingHealth',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buildingHealthFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buildingNorth',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buildingNorthFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buildingRose',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='buildingRoseFuture',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('maxerr', models.FloatField()),
                ('minerr', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='building',
            new_name='buildingWest',
        ),
        migrations.RenameModel(
            old_name='buildingFuture',
            new_name='buildingWestFuture',
        ),
    ]
