# Generated by Django 2.1.5 on 2019-04-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0016_auto_20190404_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargedcarsfraser',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargedcarsfraserfuture',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargedcarshealth',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargedcarshealthfuture',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargedcarsnorth',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargedcarsnorthfuture',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargedcarsrose',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargedcarsrosefuture',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargedcarswest',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargedcarswestfuture',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarsfraser',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarsfraserfuture',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarshealth',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarshealthfuture',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarsnorth',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarsnorthfuture',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarsrose',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarsrosefuture',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarswest',
            old_name='cars',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='chargingcarswestfuture',
            old_name='cars',
            new_name='value',
        ),
    ]
